SOUHARDYA BOSE [ DSC-LPU]
GDGVIT/airbender-backend pull request #13
Opened 2020-10-06 14:31 UTC by bose07

![S_BOSE](https://user-images.githubusercontent.com/56763840/95237470-e395f580-0825-11eb-98ec-4e4f7d24ee39.png)

2020-10-06 17:09 UTC, SaurusXI requested changes
Please use a PNG file

2020-10-06 17:19 UTC, bose07 commented
> Please use a PNG file

KINDLY CHECK, I DID.

2020-10-06 17:22 UTC, bose07 commented
kindly check, I have edited



On Tue, Oct 6, 2020 at 10:39 PM Shantanu Verma <notifications@github.com>
wrote:

> *@SaurusXI* requested changes on this pull request.
>
> Please use a PNG file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GDGVIT/airbender-backend/pull/13#pullrequestreview-503183750>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANRCLQECU4QPMPDNWQY7N7DSJNFM7ANCNFSM4SGDMOMA>
> .
>

2020-10-07 11:46 UTC, L04DB4L4NC3R commented
Done in #14

2020-10-07 11:46 UTC, closed without merging